[package]
name = "ecu-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.36.1", default-features = false, features = [
  "default_fonts",
  "glow",
  "persistence",
  "wayland",
  "x11"
]}
egui_extras = { version = "0.36.1", features = ["image"] }
image = { version = "0.25.10", default-features = false, features = ["png"] }
libc = "0.2.189"
ron = "0.12.2"

[profile.release]
opt-level = "z"
strip = true
lto = "fat"
panic = "abort"
codegen-units = 1
